### ISSUE TITLE
Unknow error while running on Mac

### ISSUE THREAD

**Issue by shlomi-viz** [wagoodman/dive#123]
Hey,

Im using version: `0.4.0`
After running: `dive 9e94d88d9015` (`9e94d88d9015` is image ID)
I got the following output:
```
Analyzing Image
  Fetching metadata...
  Fetching image...
    ├─ [layer:  0] 0063d6fb1097204 : [========================================>] 100 % (367/367)
    ├─ [layer:  1] 0cde62ef23f1d79 : [========================================>] 100 % (6806/6806)
    ├─ [layer:  2] 1e4f024eae38942 : [========================================>] 100 % (2/2)
    ├─ [layer:  3] 200beb378c77965 : [========================================>] 100 % (5515/5515)
    ├─ [layer:  4] 220caf1994dcde4 : [========================================>] 100 % (2/2)
    ├─ [layer:  5] 26dffecde589df7 : [========================================>] 100 % (379/379)
    ├─ [layer:  6] 3776d5117fdcc45 : [========================================>] 100 % (16/16)
    ├─ [layer:  7] 37e572a78946518 : [========================================>] 100 % (5/5)
    ├─ [layer:  8] 3e14becc022a564 : [========================================>] 100 % (346/346)
    ├─ [layer:  9] 4f7a09070142803 : [========================================>] 100 % (2/2)
    ├─ [layer: 10] 5013f46c80f92fb : [========================================>] 100 % (1015/1015)
    ├─ [layer: 11] 5510f61c1de8aa1 : [========================================>] 100 % (21/21)
    ├─ [layer: 12] 6bd64f41c83d24a : [========================================>] 100 % (913/913)
    ├─ [layer: 13] 6f93352f1da51b7 : [========================================>] 100 % (20/20)
    ├─ [layer: 14] 71d73e130c7ceed : [========================================>] 100 % (2/2)
    ├─ [layer: 15] 833d67504ba20c6 : [========================================>] 100 % (4812/4812)
    ├─ [layer: 16] 8724efda66c49df : [========================================>] 100 % (5/5)
    ├─ [layer: 17] 8da5dcc0564a576 : [========================================>] 100 % (3/3)
    ├─ [layer: 18] 909a0f3045db8de : [========================================>] 100 % (2/2)
    ├─ [layer: 19] 98c7904973d4ddd : [========================================>] 100 % (23872/23872)
panic: (*logrus.Entry) (0x15c1260,0xc009a43b60)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000621e0, 0xc00a49a210, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/entry.go:216 +0x2cf
github.com/sirupsen/logrus.(*Entry).Panic(0xc009a43b00, 0xc0002737e0, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/entry.go:290 +0xab
github.com/sirupsen/logrus.(*Logger).Panic(0xc0000621e0, 0xc0002737e0, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/logger.go:271 +0x6d
github.com/sirupsen/logrus.Panic(0xc0002737e0, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/exported.go:123 +0x4b
github.com/wagoodman/dive/image.InitializeData(0x7ffeefbffb2d, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/github/dive/image/image.go:210 +0x679
github.com/wagoodman/dive/cmd.analyze(0x19fdb00, 0xc000263f20, 0x1, 0x1)
	/home/wagoodman/github/dive/cmd/analyze.go:36 +0x1ab
github.com/spf13/cobra.(*Command).execute(0x19fdb00, 0xc00000a070, 0x1, 0x1, 0x19fdb00, 0xc00000a070)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x19fdb00, 0x1, 0x1c00000, 0x0)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x19fdb00, 0x19fdb00, 0xc0001b1f68)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
	/home/wagoodman/github/dive/cmd/root.go:30 +0x31
main.main()
	/home/wagoodman/github/dive/main.go:38 +0xa2
```

What is the error and how can I fix it? I'm using docker-compose to build my image, can this be a reason for this error?

**Comment by wagoodman** [comment]
This is a bug, the problem is here https://github.com/wagoodman/dive/blob/master/image/image.go#L207-L212 . I believe this is not guaranteed to read the entire json file, thus won't match the header size. I'll try and take a look later today and patch.

**Comment by wagoodman** [comment]
@shlomi-viz give v0.4.1 a shot, we can reopen this issue if it is still not working for you
