### ISSUE TITLE
dive crashes when analyzing docker image

### ISSUE THREAD

**Issue by manuel-koch** [wagoodman/dive#136]
Using dive to trigger docker build, crashing after image is built successfully.

Mac OS High Sierra, dive 0.4.0

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.10.7-gke.11
  StackAPI:         Unknown

```
Analyzing Image
  Fetching metadata...
  Fetching image...
    ├─ [layer:  0] 0e2166cb4a87a3f : [========================================>] 100 % (3897/3897)
    ├─ [layer:  1] 13d1f98ad237ccc : [========================================>] 100 % (10639/10639)
    ├─ [layer:  2] 1420189af85766a : [========================================>] 100 % (12/12)
    ├─ [layer:  3] 1ad432857f4acaa : [========================================>] 100 % (100/100)
    ├─ [layer:  4] 1f9b804742a1f03 : [========================================>] 100 % (1190/1190)
    ├─ [layer:  5] 24c56cfb191c5c9 : [========================================>] 100 % (5/5)
    ├─ [layer:  6] 49063171eec5e95 : [========================================>] 100 % (3/3)
    ├─ [layer:  7] 4fdc00100949106 : [========================================>] 100 % (17/17)
    ├─ [layer:  8] 5cb4edd17db5f76 : [========================================>] 100 % (3766/3766)
    ├─ [layer:  9] 63a8b63a2db032c : [========================================>] 100 % (17/17)
    ├─ [layer: 10] 74f5f7758660fa1 : [========================================>] 100 % (7/7)
    ├─ [layer: 11] 920bf89d0df68c1 : [========================================>] 100 % (130/130)
    ├─ [layer: 12] 92faeea8b476580 : [========================================>] 100 % (4/4)
    ├─ [layer: 13] aba60eb9d6215a0 : [========================================>] 100 % (1994/1994)
    ├─ [layer: 14] c87ffdbebfc589f : [========================================>] 100 % (12/12)
    ├─ [layer: 15] c99c11c35575a33 : [========================================>] 100 % (714/714)
    ├─ [layer: 16] d79ac99101883c3 : [========================================>] 100 % (5/5)
    ├─ [layer: 17] da78dafa4701fee : [========================================>] 100 % (12/12)
    ├─ [layer: 18] db8b51066bcbc50 : [========================================>] 100 % (18/18)
    ├─ [layer: 19] e3b2158edfadd18 : [========================================>] 100 % (15/15)
    ├─ [layer: 20] f553764df4db3cd : [========================================>] 100 % (12/12)
panic: (*logrus.Entry) (0x15c1260,0xc000081140)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000a4180, 0xc0018f5320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/entry.go:216 +0x2cf
github.com/sirupsen/logrus.(*Entry).Panic(0xc0000810e0, 0xc000219778, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/entry.go:290 +0xab
github.com/sirupsen/logrus.(*Logger).Panic(0xc0000a4180, 0xc000219778, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/logger.go:271 +0x6d
github.com/sirupsen/logrus.Panic(0xc000219778, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/exported.go:123 +0x4b
github.com/wagoodman/dive/image.InitializeData(0xc00008ca00, 0x47, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/github/dive/image/image.go:210 +0x679
github.com/wagoodman/dive/cmd.doBuild(0x19fd8a0, 0xc0002f2900, 0x3, 0x3)
	/home/wagoodman/github/dive/cmd/build.go:50 +0x3b7
github.com/spf13/cobra.(*Command).execute(0x19fd8a0, 0xc0002f2900, 0x3, 0x3, 0x19fd8a0, 0xc0002f2900)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x19fdb00, 0x1, 0x1c006c0, 0x0)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x19fdb00, 0x19fdb00, 0xc0001ddf68)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
	/home/wagoodman/github/dive/cmd/root.go:30 +0x31
main.main()
	/home/wagoodman/github/dive/main.go:38 +0xa2
```

Inspecting the image using "dive <IMAGE_NAME>" after it has been built crashes too with same callstack.

(Re)building the image using plain "docker build" ( but docker didn't do anything because every layer was still cached ).
Inspecting the image using "dive <IMAGE_NAME>" after it has been built again does not crash !?

```
Analyzing Image
  Fetching metadata...
  Fetching image...
    ├─ [layer:  0] 0e2166cb4a87a3f : [========================================>] 100 % (3897/3897)
    ├─ [layer:  1] 13d1f98ad237ccc : [========================================>] 100 % (10639/10639)
    ├─ [layer:  2] 1420189af85766a : [========================================>] 100 % (12/12)
    ├─ [layer:  3] 1ad432857f4acaa : [========================================>] 100 % (100/100)
    ├─ [layer:  4] 1f9b804742a1f03 : [========================================>] 100 % (1190/1190)
    ├─ [layer:  5] 24c56cfb191c5c9 : [========================================>] 100 % (5/5)
    ├─ [layer:  6] 49063171eec5e95 : [========================================>] 100 % (3/3)
    ├─ [layer:  7] 4fdc00100949106 : [========================================>] 100 % (17/17)
    ├─ [layer:  8] 5cb4edd17db5f76 : [========================================>] 100 % (3766/3766)
    ├─ [layer:  9] 63a8b63a2db032c : [========================================>] 100 % (17/17)
    ├─ [layer: 10] 74f5f7758660fa1 : [========================================>] 100 % (7/7)
    ├─ [layer: 11] 920bf89d0df68c1 : [========================================>] 100 % (130/130)
    ├─ [layer: 12] 92faeea8b476580 : [========================================>] 100 % (4/4)
    ├─ [layer: 13] aba60eb9d6215a0 : [========================================>] 100 % (1994/1994)
    ├─ [layer: 14] c87ffdbebfc589f : [========================================>] 100 % (12/12)
    ├─ [layer: 15] c99c11c35575a33 : [========================================>] 100 % (714/714)
    ├─ [layer: 16] d79ac99101883c3 : [========================================>] 100 % (5/5)
    ├─ [layer: 17] da78dafa4701fee : [========================================>] 100 % (12/12)
    ├─ [layer: 18] db8b51066bcbc50 : [========================================>] 100 % (18/18)
    ├─ [layer: 19] e3b2158edfadd18 : [========================================>] 100 % (15/15)
    ├─ [layer: 20] f553764df4db3cd : [========================================>] 100 % (12/12)
    ╧
  Building tree...
  Analyzing layers...
```

**Comment by manuel-koch** [comment]
Rebuild my image ( incl. changes in image layers ) using plain "docker build" and afterwards running "dive <IMAGE>" crashes again.
Looks like something in the image triggers dive to crash, regardless how it gets built...

```
Analyzing Image
  Fetching metadata...
  Fetching image...
    ├─ [layer:  0] 13d1f98ad237ccc : [========================================>] 100 % (10639/10639)
    ├─ [layer:  1] 1420189af85766a : [========================================>] 100 % (12/12)
    ├─ [layer:  2] 1ad432857f4acaa : [========================================>] 100 % (100/100)
    ├─ [layer:  3] 1f9b804742a1f03 : [========================================>] 100 % (1190/1190)
    ├─ [layer:  4] 24c56cfb191c5c9 : [========================================>] 100 % (5/5)
    ├─ [layer:  5] 49063171eec5e95 : [========================================>] 100 % (3/3)
    ├─ [layer:  6] 4fdc00100949106 : [========================================>] 100 % (17/17)
    ├─ [layer:  7] 5cb4edd17db5f76 : [========================================>] 100 % (3766/3766)
    ├─ [layer:  8] 63a8b63a2db032c : [========================================>] 100 % (17/17)
    ├─ [layer:  9] 74f5f7758660fa1 : [========================================>] 100 % (7/7)
    ├─ [layer: 10] 920bf89d0df68c1 : [========================================>] 100 % (130/130)
    ├─ [layer: 11] a743298e9dd5ce1 : [========================================>] 100 % (4/4)
    ├─ [layer: 12] aba60eb9d6215a0 : [========================================>] 100 % (1994/1994)
    ├─ [layer: 13] abc2b7c4a42aa89 : [========================================>] 100 % (3897/3897)
    ├─ [layer: 14] c87ffdbebfc589f : [========================================>] 100 % (12/12)
    ├─ [layer: 15] c99c11c35575a33 : [========================================>] 100 % (714/714)
    ├─ [layer: 16] da78dafa4701fee : [========================================>] 100 % (12/12)
    ├─ [layer: 17] db8b51066bcbc50 : [========================================>] 100 % (18/18)
    ├─ [layer: 18] e3b2158edfadd18 : [========================================>] 100 % (15/15)
panic: (*logrus.Entry) (0x15c1260,0xc000200ea0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00006a1e0, 0xc000caf980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/entry.go:216 +0x2cf
github.com/sirupsen/logrus.(*Entry).Panic(0xc000200d80, 0xc0002757e0, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/entry.go:290 +0xab
github.com/sirupsen/logrus.(*Logger).Panic(0xc00006a1e0, 0xc0002757e0, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/logger.go:271 +0x6d
github.com/sirupsen/logrus.Panic(0xc0002757e0, 0x1, 0x1)
	/home/wagoodman/go/pkg/mod/github.com/sirupsen/logrus@v1.2.0/exported.go:123 +0x4b
github.com/wagoodman/dive/image.InitializeData(0x7ffeefbff82d, 0x23, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/github/dive/image/image.go:210 +0x679
github.com/wagoodman/dive/cmd.analyze(0x19fdb00, 0xc000265f20, 0x1, 0x1)
	/home/wagoodman/github/dive/cmd/analyze.go:36 +0x1ab
github.com/spf13/cobra.(*Command).execute(0x19fdb00, 0xc00000a070, 0x1, 0x1, 0x19fdb00, 0xc00000a070)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x19fdb00, 0x1, 0x1d00000, 0x0)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x19fdb00, 0x19fdb00, 0xc0001b3f68)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
	/home/wagoodman/github/dive/cmd/root.go:30 +0x31
main.main()
	/home/wagoodman/github/dive/main.go:38 +0xa2
```

**Comment by manuel-koch** [comment]
rebuilding docker image again ( some custom file in image changed ) - using "dive <IMAGE>" without crash...

**Comment by wagoodman** [comment]
Mind pulling the latest 0.5.0 changes and trying again? There were a lot of changes in this area in the next version.

**Comment by manuel-koch** [comment]
I have tried many of my built docker images using dive 0.5.0 and did not get this error again.
Thanks !

**Comment by wagoodman** [comment]
Good to hear! Feel free to open this issue (or a new one) if you see this again.
