### ISSUE TITLE
Crashes on image analysis (SIGSEV wagoodman/dive/image.(*dockerLayer).Size(...))

### ISSUE THREAD

**Issue by anthonydahanne** [wagoodman/dive#169]
Hello,
I've tried analyzing this image using dive (anthonydahanne/dive:sigsegv) and it broke .
This issue is similar to https://github.com/wagoodman/dive/issues/35 ; but I'm not sure it's exactly the same issue.

```
$ dive -v
dive 0.6.0
$ dive anthonydahanne/dive:sigsegv
Fetching image...
Parsing image...
  ├─ [layer:  1] 1b0bce5d8cb16c9 : [==============================>] 100 % (1/1)
  ├─ [layer:  2] 39fee0af5d411b8 : [==============================>] 100 % (589/589)
  ├─ [layer:  3] 3f9060bfaaf5fd2 : [==============================>] 100 % (20/20)
  ├─ [layer:  4] 48c3b80377333c5 : [==============================>] 100 % (20/20)
  ├─ [layer:  5] 4bb3e7c2f469d23 : [==============================>] 100 % (7/7)
  ├─ [layer:  6] 4eec1208b4eaa27 : [==============================>] 100 % (6/6)
  ├─ [layer:  7] 4f1b072e2a06218 : [==============================>] 100 % (2/2)
  ├─ [layer:  8] 5c1bf18375d13b8 : [==============================>] 100 % (733/733)
  ├─ [layer:  9] 9589b003443c788 : [==============================>] 100 % (3306/3306)
  ├─ [layer: 10] a5d343159e1cbbd : [==============================>] 100 % (1/1)
  ├─ [layer: 11] b7e6f52d2cb9761 : [==============================>] 100 % (3/3)
  ├─ [layer: 12] d75ee6f5db71608 : [==============================>] 100 % (3/3)
  ├─ [layer: 13] e5d20e2c8684907 : [==============================>] 100 % (24/24)
  ├─ [layer: 14] e91ca14b77ebdf7 : [==============================>] 100 % (3003/3003)
  ╧
Analyzing image...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13f4057]

goroutine 1 [running]:
github.com/wagoodman/dive/image.(*dockerLayer).Size(...)
	/home/wagoodman/github/dive/image/docker_layer.go:31
github.com/wagoodman/dive/image.(*dockerImageAnalyzer).Analyze(0xc00022b1a0, 0x1, 0x1, 0x1b)
	/home/wagoodman/github/dive/image/docker_image.go:170 +0x597
github.com/wagoodman/dive/runtime.Run(0x7ffeefbff885, 0x1b, 0x0, 0x0, 0x15de01f, 0x8, 0x0, 0x0, 0x0)
	/home/wagoodman/github/dive/runtime/run.go:103 +0x4f4
github.com/wagoodman/dive/cmd.doAnalyzeCmd(0x1a14ae0, 0xc00028df70, 0x1, 0x1)
	/home/wagoodman/github/dive/cmd/analyze.go:33 +0x135
github.com/spf13/cobra.(*Command).execute(0x1a14ae0, 0xc0000a6010, 0x1, 0x1, 0x1a14ae0, 0xc0000a6010)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1a14ae0, 0x1, 0x1b19d80, 0x0)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1a14ae0, 0x1a14ae0, 0xc0001dbf68)
	/home/wagoodman/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
	/home/wagoodman/github/dive/cmd/root.go:33 +0x31
main.main()
	/home/wagoodman/github/dive/main.go:38 +0xa2
```

**Comment by wagoodman** [comment]
It appears that your image doesn't have a history captured:
```
$ docker history anthonydahanne/dive:sigsegv
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
```
It seems that this is a symptom of building your image via buildpack. I can fix dive to not be dependent on the image history, however, the commands that caused each layer change won't be displayed on the UI. A fix for this will be in the next release (0.7.0).
