### ISSUE TITLE
Support remote docker installations

### ISSUE THREAD

**Issue by mwidmann** [wagoodman/dive#29]
The docker client can be set up to connect to a docker server remotely using the value specified in the `DOCKER_HOST` env variable, (e.g. `DOCKER_HOST=tcp://127.0.0.1:2375`)

This can be useful if you have a Windows machine running Docker and WSL connecting to it. Having this setup and trying to dive into a docker image, produces the error:

```
❯ dive jenkins/jenkins:latest
dive jenkins/jenkins:latest
Analyzing Image
latest: Pulling from jenkins/jenkins
Digest: sha256:5d9450a3b391e96a1525f6a5b40b3e2095df7a19195b6341fb097120cb0ab099
Status: Image is up to date for jenkins/jenkins:latest
  Fetching metadata...
  Fetching image...panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(0x9d6de0, 0xc4202a9f60)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:27 +0x4a
github.com/wagoodman/dive/image.saveImage(0x7fffcd788c0c, 0x16, 0x0, 0x0, 0x0, 0x0)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:356 +0x3cd
github.com/wagoodman/dive/image.InitializeData(0x7fffcd788c0c, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:215 +0x218
github.com/wagoodman/dive/cmd.analyze(0xc47fe0, 0xc4202a9bb0, 0x1, 0x1)
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:21 +0xfc
github.com/spf13/cobra.(*Command).execute(0xc47fe0, 0xc42000c070, 0x1, 0x1, 0xc47fe0, 0xc42000c070)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc47fe0, 0x1, 0x1, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc47fe0, 0xc420088058, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:28 +0x2d
main.main()
        /home/wagoodman/go/src/github.com/wagoodman/dive/main.go:34 +0x20
```

Would it be feasible to use the value specified in `DOCKER_HOST` (if present) to connect to the docker server?

edit: replaced `DOCKER_HOME` with `DOCKER_HOST` to avoid any comprehension errors..

**Comment by wagoodman** [comment]
by `DOCKER_HOME` do you mean `DOCKER_HOST`? if so, indeed this sounds pretty sensible. I'll try to support a more env-driven docker client connection.

**Comment by mwidmann** [comment]
Yes, I meant `DOCKER_HOST` which is used by the docker client if set. See also https://docs.docker.com/engine/reference/commandline/cli/#description

**Comment by wagoodman** [comment]
it appears that the default client already supports reading the DOCKER_HOST from the environment. Can you verify that the env var is set @mwidmann ?

**Comment by nlowe** [comment]
@wagoodman It's set on my box but `dive` is still trying to use `/var/run/docker.sock`:

```bash
nathan@DESKTOP-SPO9J0T:/c/Users/Nathan/projects/Win10-Initial-Setup-Script$ dive busybox
Analyzing Image
Using default tag: latest
latest: Pulling from library/busybox
Digest: sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
Status: Image is up to date for busybox:latest
  Fetching metadata...
  Fetching image...panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(0x9d8160, 0xc4202c5f90)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:28 +0x4a
github.com/wagoodman/dive/image.saveImage(0x7fffe461bcdc, 0x7, 0x0, 0x0, 0x0, 0x0)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:357 +0x3cd
github.com/wagoodman/dive/image.InitializeData(0x7fffe461bcdc, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:216 +0x218
github.com/wagoodman/dive/cmd.analyze(0xc49040, 0xc4202c5be0, 0x1, 0x1)
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:36 +0x119
github.com/spf13/cobra.(*Command).execute(0xc49040, 0xc42000c070, 0x1, 0x1, 0xc49040, 0xc42000c070)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc49040, 0x2, 0x7f1681370000, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc49040, 0xc4201e1f78, 0xc4201e1f58)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:29 +0x2d
main.main()
        /home/wagoodman/go/src/github.com/wagoodman/dive/main.go:38 +0xad
nathan@DESKTOP-SPO9J0T:/c/Users/Nathan/projects/Win10-Initial-Setup-Script$ echo $DOCKER_HOST
tcp://0.0.0.0:2375
```

**Comment by nlowe** [comment]
What's weird is it can get the metadata and pull images that I don't have:

```bash
nathan@DESKTOP-SPO9J0T:/c/Users/Nathan/projects/Win10-Initial-Setup-Script$ dive ubuntu
Analyzing Image
Using default tag: latest
latest: Pulling from library/ubuntu
473ede7ed136: Pull complete
c46b5fa4d940: Pull complete
93ae3df89c92: Pull complete
6b1eed27cade: Pull complete
Digest: sha256:29934af957c53004d7fb6340139880d23fb1952505a15d69a03af0d1418878cb
Status: Downloaded newer image for ubuntu:latest
  Fetching metadata...
  Fetching image...panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(0x9d8160, 0xc4202c5f80)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:28 +0x4a
github.com/wagoodman/dive/image.saveImage(0x7fffc6b490dc, 0x6, 0x0, 0x0, 0x0, 0x0)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:357 +0x3cd
github.com/wagoodman/dive/image.InitializeData(0x7fffc6b490dc, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:216 +0x218
github.com/wagoodman/dive/cmd.analyze(0xc49040, 0xc4202c5bd0, 0x1, 0x1)
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:36 +0x119
github.com/spf13/cobra.(*Command).execute(0xc49040, 0xc42000c070, 0x1, 0x1, 0xc49040, 0xc42000c070)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc49040, 0x2, 0x7fdb597d0000, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc49040, 0xc4201e1f78, 0xc4201e1f58)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:29 +0x2d
main.main()
        /home/wagoodman/go/src/github.com/wagoodman/dive/main.go:38 +0xad
```

**Comment by nlowe** [comment]
Looking into the client codebase more, I believe the client customization needs to also specify [`FromEnv`](https://godoc.org/github.com/docker/docker/client#FromEnv) when constructing the client (if you want to specify a client version, otherwise you can just use [`NewEnvClient`](https://godoc.org/github.com/docker/docker/client#NewEnvClient)):

```go
dockerClient, err := client.NewClientWithOpts(client.WithVersion(dockerVersion), client.FromEnv)
```

**Comment by mwidmann** [comment]
@wagoodman the environment variable is set, otherwise the docker cli client wouldn't work inside WSL.

```
~
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch

~
❯ echo $DOCKER_HOST
tcp://127.0.0.1:2375

~
❯ dive jenkins/jenkins
Analyzing Image
Using default tag: latest
latest: Pulling from jenkins/jenkins
Digest: sha256:8b25e9073cf6be9c7dffcc47fa06db454304cb6b6b3e93d71f55b8c994ec602c
Status: Image is up to date for jenkins/jenkins:latest
  Fetching metadata...
  Fetching image...panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(0x9d6de0, 0xc4202b7f50)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:27 +0x4a
github.com/wagoodman/dive/image.saveImage(0x7ffff573309c, 0xf, 0x0, 0x0, 0x0, 0x0)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:356 +0x3cd
github.com/wagoodman/dive/image.InitializeData(0x7ffff573309c, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:215 +0x218
github.com/wagoodman/dive/cmd.analyze(0xc47fe0, 0xc4202b7ba0, 0x1, 0x1)
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:21 +0xfc
github.com/spf13/cobra.(*Command).execute(0xc47fe0, 0xc42000c070, 0x1, 0x1, 0xc47fe0, 0xc42000c070)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc47fe0, 0x1, 0x1, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc47fe0, 0xc420096058, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:28 +0x2d
main.main()
        /home/wagoodman/go/src/github.com/wagoodman/dive/main.go:34 +0x20
```

**Comment by wagoodman** [comment]
@nlowe nice! I should read the docs a bit more closely nextime. I noticed this https://godoc.org/github.com/docker/docker/client#pkg-constants and this https://github.com/moby/moby/blob/master/client/client.go#L250 which was a bit misleading.
