### ISSUE TITLE
Client API version is newer than the supported Daemon version

### ISSUE THREAD

**Issue by warmchang** [wagoodman/dive#47]
Dive is an very useful tool, and hope to support the offline analysis.

(Eg: add a parameter alwayspullimage: True/False) :smiley: 

```
 ⚡ root@k8s  /home/ubuntu  docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
busybox                  latest              59788edf1f3e        3 weeks ago         1.154 MB
alpine                   3.8                 196d12cf6ab1        6 weeks ago         4.413 MB
k8s.gcr.io/pause-amd64   3.1                 da86e6ba6ca1        10 months ago       742.5 kB
k8s.gcr.io/pause         3.1                 da86e6ba6ca1        10 months ago       742.5 kB
 ⚡ root@k8s  /home/ubuntu  dive --version
dive 0.0.8
 ⚡ root@k8s  /home/ubuntu  dive busybox:latest
Analyzing Image
Pulling repository docker.io/library/busybox
Error while pulling image: Get https://index.docker.io/v1/repositories/library/busybox/images: dial tcp: lookup index.docker.io on 192.168.1.100:53: server misbehaving
  Fetching metadata...
  Fetching image...panic: Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(0x9d74c0, 0xc4203d4120)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:28 +0x4a
github.com/wagoodman/dive/image.saveImage(0x7ffdc5c4d7b5, 0xe, 0x0, 0x0, 0x0, 0x0)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:357 +0x3cd
github.com/wagoodman/dive/image.InitializeData(0x7ffdc5c4d7b5, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:216 +0x218
github.com/wagoodman/dive/cmd.analyze(0xc49040, 0xc4202abbe0, 0x1, 0x1)
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:36 +0x119
github.com/spf13/cobra.(*Command).execute(0xc49040, 0xc42000c090, 0x1, 0x1, 0xc49040, 0xc42000c090)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc49040, 0x2, 0x7f1e99c02000, 0x0)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc49040, 0xc4201c9f78, 0xc4201c9f58)
        /home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
        /home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:29 +0x2d
main.main()
        /home/wagoodman/go/src/github.com/wagoodman/dive/main.go:38 +0xad
 ✘ ⚡ root@k8s  /home/ubuntu 
```

**Comment by wagoodman** [comment]
Dive doesn't look for anything online (other than a docker pull if the image doesn't exist), instead this error is indicating that the requested client API version is newer than your local Docker Daemon.

This is similar to #29 in the sense that the client should be a bit more intelligent.
