### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by michbsd** [wagoodman/dive#79]
Hi,

Just installed on Mac (mojave) 

```
brew install dive                          
==> Installing dive from wagoodman/dive
==> Downloading https://github.com/wagoodman/dive/releases/download/v0.3.0/dive_0.3.0_darw
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/13325
######################################################################## 100.0%
🍺  /usr/local/Cellar/dive/0.3.0: 5 files, 10.7MB, built in 6 seconds
```

This is what happens when trying to attach to a container : 

```
~/Dropbox/code> docker container ls | grep redis                                
876ded7dfe64        gcr.io/xxx-staging/redis-cluster/redis-cluster:5.0.1-v1   "/docker-entrypoint.…"   4 days ago          Up 4 days           6379/tcp, 0.0.0.0:7000-7005->7000-7005/tcp    redis-cluster
~/Dropbox/code> dive 876ded7dfe64
Analyzing Image
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable
  Fetching metadata...
  Fetching image...panic: Error response from daemon: No such image: 876ded7dfe64

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(...)
	/home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:29
github.com/wagoodman/dive/image.saveImage(0x7ffeefbff87d, 0xc, 0x0, 0x0, 0x0, 0x0)
	/home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:358 +0xccc
github.com/wagoodman/dive/image.InitializeData(0x7ffeefbff87d, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:217 +0x1cb
github.com/wagoodman/dive/cmd.analyze(0x19d8e40, 0xc00028fee0, 0x1, 0x1)
	/home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:36 +0x1ab
github.com/spf13/cobra.(*Command).execute(0x19d8e40, 0xc0000a6010, 0x1, 0x1, 0x19d8e40, 0xc0000a6010)
	/home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x19d8e40, 0x1, 0x1c00d80, 0x0)
	/home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x19d8e40, 0x19d8e40, 0xc0001ddf68)
	/home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
	/home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:30 +0x2d
main.main()
	/home/wagoodman/go/src/github.com/wagoodman/dive/main.go:38 +0xa2
```

**Comment by michbsd** [comment]
Doh! Not container-id but container-tag. 

Sorry for the noise.
